version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8000:8000"
    links: 
      - "db:database"
    networks:
      - my-network
  db:
    image: postgres
    build: ./docker/db
    ports:
      - "8001:5432"
    networks:
      - my-network

networks:
  my-network:
    external: true