version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "4002:4000"
    networks:
      - my-network
    restart: always
    volumes:
      - ./logs:/logs
  db:
    image: postgres
    build: ./docker/db
    ports:
      - "8001:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
     - .:/code
    networks:
      - my-network
  redis:
    image: "redis:alpine"
volumes:
  myapp:
    external: true
networks:
  my-network:
    external: true